name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      AWS_DEFAULT_REGION: us-west-2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        mkdir -p lint
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=119 --statistics --output=lint/flake8-${{ matrix.python-version }}.out
    - name: Archive lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint-reports
        path: lint/flake8-*.out
    - name: Test with pytest
      run: |
        pytest tests/ --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=aws_sso --cov-report=xml:coverage-reports/coverage-${{ matrix.python-version }}.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: coverage-reports/coverage-*.xml
    - name: Archive test coverage results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: junit/test-results-*.xml

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Download lint-reports
        uses: actions/download-artifact@v2
        with:
          name: lint-reports
          path: lint/
      - name: Download coverage-reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: coverage-reports/
      - name: Download test-reports
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: junit/
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}